version: '2'
services:  
  liao_r12n:
    build:
      context: "${PWD}/Demo3"
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    networks:
      - "fx"
    depends_on:
      - liao_fx_redis
      - liao_fx_postgres
    restart: always
  liao_fx_redis:
    image: redis:latest
    networks:
      - "fx"
  liao_fx_postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=demois1207
    networks:
      - "fx"
networks:
  fx:
 