version: '2'
services:  
  liaor12n:
    build:
      context: "${PWD}/Demo3"
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    networks:
      - "fx"
    depends_on:
      - liaofxredis
      - liaofxpostgres
    restart: always
  liaofxredis:
    image: redis:latest
    networks:
      - "fx"
  liaofxpostgres:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=demois1207
    networks:
      - "fx"
networks:
  fx:
 