version: '2'
services:  
  liao_r12n:
    image: scenariorec_liaor12n
    container_name: scenariorec_liaor12n_1
    ports:
      - "3010:80"
    networks:
      - "fx"
    depends_on:
      - liaofxredis
      - liaofxpostgres
    restart: always
  liaofxredis:
    image: redis:latest
    networks:
      - "fx"
  liaofxpostgres:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=demois1207
    networks:
      - "fx"
networks:
  fx:
 
